import type { Job } from "@/types";

// ────────────────────────────────────────────────
// Mock Job data for homepage sections
// Each object satisfies the full `Job` interface
// so it can be passed directly to `openJob(job)`
// ────────────────────────────────────────────────

// ─── Featured ──────────────────────────────────

export const featuredHeroJob: Job = {
  id: "feat-hero-1",
  slug: "senior-product-manager-mpesa-safaricom-nairobi",
  title: "Senior Product Manager — M-Pesa",
  companyName: "Safaricom PLC",
  companyVerified: true,
  location: "Nairobi",
  county: "Nairobi",
  category: "Product Management",
  subcategory: "Mobile Payments",
  listingType: "JOB",
  employmentType: "Full-time",
  experienceLevel: "Senior",
  workMode: "HYBRID",
  salaryMin: 350000,
  salaryMax: 550000,
  salaryPeriod: "month",
  description:
    "<p>Lead product strategy for M-Pesa, serving 30M+ active users across East Africa. You will own the product roadmap, work closely with a cross-functional team of 12+ engineers and designers, and drive key initiatives in financial inclusion, lending, and merchant payments.</p><ul><li>Define and execute the M-Pesa product vision and roadmap</li><li>Analyze market trends, user behavior, and competitive landscape</li><li>Collaborate with engineering, design, and business teams</li><li>Drive A/B testing and data-informed product decisions</li><li>Present product strategy to C-suite stakeholders</li></ul>",
  tags: ["Product Management", "Fintech", "M-Pesa", "Mobile Payments", "Senior"],
  createdAt: "2025-01-15T09:00:00Z",
  deadline: "2025-03-15T23:59:00Z",
  featured: true,
};

export const featuredJobs: Job[] = [
  {
    id: "feat-1",
    slug: "financial-analyst-equity-bank-nairobi",
    title: "Financial Analyst",
    companyName: "Equity Bank",
    companyVerified: true,
    location: "Nairobi",
    county: "Nairobi",
    category: "Finance & Accounting",
    listingType: "JOB",
    employmentType: "Full-time",
    experienceLevel: "Mid-level",
    workMode: "ONSITE",
    salaryMin: 120000,
    salaryMax: 180000,
    salaryPeriod: "month",
    description:
      "<p>Join Equity Bank's Strategic Planning division as a Financial Analyst. You will support investment decisions, financial modeling, and reporting across the bank's East Africa operations.</p><ul><li>Build and maintain financial models for business planning</li><li>Prepare management reports and board presentations</li><li>Conduct market research and competitive analysis</li><li>Support budget forecasting and variance analysis</li></ul>",
    tags: ["Finance", "Banking", "Financial Analysis", "CPA"],
    createdAt: "2025-02-01T10:00:00Z",
    deadline: "2025-03-01T23:59:00Z",
    featured: true,
  },
  {
    id: "feat-2",
    slug: "software-engineer-kcb-bank-remote",
    title: "Software Engineer",
    companyName: "KCB Bank",
    companyVerified: true,
    location: "Remote",
    county: "Nairobi",
    category: "Software Engineering",
    subcategory: "Backend",
    listingType: "JOB",
    employmentType: "Full-time",
    experienceLevel: "Mid-level",
    workMode: "REMOTE",
    salaryMin: 200000,
    salaryMax: 350000,
    salaryPeriod: "month",
    description:
      "<p>Build the next generation of KCB's digital banking platform. Work with modern microservices architecture, cloud infrastructure, and agile delivery teams.</p><ul><li>Design and develop RESTful APIs and microservices</li><li>Implement secure payment processing solutions</li><li>Write unit and integration tests</li><li>Participate in code reviews and technical design discussions</li></ul>",
    tags: ["Software Engineering", "Backend", "Java", "Remote", "Fintech"],
    createdAt: "2025-01-28T08:00:00Z",
    deadline: "2025-03-10T23:59:00Z",
    featured: true,
  },
  {
    id: "feat-3",
    slug: "graduate-trainee-ncba-group-nairobi",
    title: "Graduate Trainee",
    companyName: "NCBA Group",
    companyVerified: true,
    location: "Nairobi",
    county: "Nairobi",
    category: "Graduate Programs",
    listingType: "JOB",
    employmentType: "Full-time",
    experienceLevel: "Entry-level",
    workMode: "ONSITE",
    description:
      "<p>NCBA Group's 12-month Graduate Trainee Program offers recent graduates hands-on experience in banking operations, digital innovation, and leadership development. Successful candidates rotate across multiple departments.</p><ul><li>Rotate through Retail Banking, Corporate Banking, and Operations</li><li>Participate in leadership and professional development workshops</li><li>Contribute to digital transformation projects</li><li>Receive mentorship from senior executives</li></ul>",
    tags: ["Graduate", "Trainee", "Banking", "Entry Level"],
    createdAt: "2025-02-05T11:00:00Z",
    deadline: "2025-03-20T23:59:00Z",
    featured: true,
  },
];

// ─── Closing Soon ──────────────────────────────

export const closingSoonJobs: Job[] = [
  {
    id: "close-1",
    slug: "marketing-intern-ncba-group-nairobi",
    title: "Marketing Intern",
    companyName: "NCBA Group",
    companyVerified: true,
    location: "Nairobi",
    county: "Nairobi",
    category: "Marketing & Communications",
    listingType: "OPPORTUNITY",
    opportunityType: "INTERNSHIP",
    employmentType: "Internship",
    experienceLevel: "Entry-level",
    workMode: "ONSITE",
    salaryMin: 15000,
    salaryMax: 25000,
    salaryPeriod: "month",
    description:
      "<p>Join NCBA's Marketing department for a 3-month internship. Gain exposure to brand management, digital marketing campaigns, and corporate communications.</p><ul><li>Assist in planning and executing marketing campaigns</li><li>Create content for social media platforms</li><li>Support market research and competitor analysis</li><li>Help organize corporate events and sponsorships</li></ul>",
    tags: ["Marketing", "Internship", "Social Media"],
    createdAt: "2025-01-20T14:00:00Z",
    deadline: "2025-02-20T23:59:00Z",
    featured: false,
  },
  {
    id: "close-2",
    slug: "senior-accountant-safaricom-nairobi",
    title: "Senior Accountant",
    companyName: "Safaricom",
    companyVerified: true,
    location: "Nairobi",
    county: "Nairobi",
    category: "Finance & Accounting",
    listingType: "JOB",
    employmentType: "Full-time",
    experienceLevel: "Senior",
    workMode: "HYBRID",
    salaryMin: 180000,
    salaryMax: 280000,
    salaryPeriod: "month",
    description:
      "<p>Join Safaricom's Finance division as a Senior Accountant. Oversee financial reporting, tax compliance, and internal audit processes for one of East Africa's largest companies.</p>",
    tags: ["Accounting", "CPA", "Senior", "Finance"],
    createdAt: "2025-01-25T09:00:00Z",
    deadline: "2025-02-25T23:59:00Z",
    featured: false,
  },
  {
    id: "close-3",
    slug: "hr-manager-equity-bank-nairobi",
    title: "HR Manager",
    companyName: "Equity Bank",
    companyVerified: true,
    location: "Nairobi",
    county: "Nairobi",
    category: "Human Resources",
    listingType: "JOB",
    employmentType: "Full-time",
    experienceLevel: "Senior",
    workMode: "ONSITE",
    salaryMin: 200000,
    salaryMax: 320000,
    salaryPeriod: "month",
    description:
      "<p>Lead the HR function for Equity Bank's Nairobi region, managing talent acquisition, employee relations, performance management, and organizational development for 500+ staff.</p>",
    tags: ["HR", "Management", "Banking", "Senior"],
    createdAt: "2025-01-22T10:00:00Z",
    deadline: "2025-02-28T23:59:00Z",
    featured: false,
  },
  {
    id: "close-4",
    slug: "junior-developer-kcb-bank-nairobi",
    title: "Junior Developer",
    companyName: "KCB Bank",
    companyVerified: true,
    location: "Nairobi",
    county: "Nairobi",
    category: "Software Engineering",
    listingType: "JOB",
    employmentType: "Full-time",
    experienceLevel: "Entry-level",
    workMode: "ONSITE",
    salaryMin: 80000,
    salaryMax: 120000,
    salaryPeriod: "month",
    description:
      "<p>KCB Bank is looking for enthusiastic Junior Developers to join our technology team. You will work on internal tools, customer-facing applications, and gain exposure to enterprise software development.</p>",
    tags: ["Software Engineering", "Junior", "Entry Level"],
    createdAt: "2025-01-18T12:00:00Z",
    deadline: "2025-03-05T23:59:00Z",
    featured: false,
  },
  {
    id: "close-5",
    slug: "data-analyst-kra-nairobi",
    title: "Data Analyst",
    companyName: "KRA",
    companyVerified: true,
    location: "Nairobi",
    county: "Nairobi",
    category: "Data Science & Analytics",
    listingType: "GOVERNMENT",
    governmentLevel: "NATIONAL",
    employmentType: "Full-time",
    experienceLevel: "Mid-level",
    workMode: "ONSITE",
    salaryMin: 100000,
    salaryMax: 160000,
    salaryPeriod: "month",
    description:
      "<p>KRA is seeking a Data Analyst to support revenue intelligence and compliance analytics. You will work with large datasets to identify tax compliance patterns and support policy decisions.</p>",
    tags: ["Data", "Analytics", "Government", "Tax"],
    createdAt: "2025-01-19T08:00:00Z",
    deadline: "2025-03-05T23:59:00Z",
    featured: false,
  },
];

// ─── Government ─────────────────────────────────

export const nationalGovJobs: Job[] = [
  {
    id: "gov-1",
    slug: "kra-graduate-trainee-program-2025",
    title: "KRA Graduate Trainee Program 2025",
    companyName: "Kenya Revenue Authority",
    companyVerified: true,
    location: "Nairobi",
    county: "Nairobi",
    category: "Government & Public Service",
    listingType: "GOVERNMENT",
    governmentLevel: "NATIONAL",
    employmentType: "Full-time",
    experienceLevel: "Entry-level",
    workMode: "ONSITE",
    description:
      "<p>The Kenya Revenue Authority invites applications from qualified graduates for its 2025 Graduate Trainee Program. The program runs for 18 months and offers rotations across Customs, Domestic Taxes, and IT departments.</p><ul><li>Rotate through multiple KRA departments</li><li>Receive comprehensive training on tax administration</li><li>Work on real revenue collection projects</li><li>Get mentorship from senior officers</li></ul>",
    tags: ["Government", "KRA", "Graduate", "National"],
    createdAt: "2025-01-10T07:00:00Z",
    deadline: "2025-02-15T23:59:00Z",
    featured: false,
  },
  {
    id: "gov-2",
    slug: "tsc-5000-teacher-posts-2025",
    title: "TSC — 5,000 Teacher Posts",
    companyName: "Teachers Service Commission",
    companyVerified: true,
    location: "Nationwide",
    county: "Nairobi",
    category: "Education & Training",
    listingType: "GOVERNMENT",
    governmentLevel: "NATIONAL",
    employmentType: "Full-time",
    experienceLevel: "Entry-level",
    workMode: "ONSITE",
    description:
      "<p>The Teachers Service Commission has advertised 5,000 teaching positions for secondary schools across all 47 counties. Positions are available for various subject combinations.</p>",
    tags: ["Government", "TSC", "Teaching", "Education"],
    createdAt: "2025-01-12T08:00:00Z",
    deadline: "2025-02-28T23:59:00Z",
    featured: false,
  },
  {
    id: "gov-3",
    slug: "kenya-police-constable-recruitment-2025",
    title: "Kenya Police Constable Recruitment",
    companyName: "National Police Service",
    companyVerified: true,
    location: "Nationwide",
    county: "Nairobi",
    category: "Security & Law Enforcement",
    listingType: "GOVERNMENT",
    governmentLevel: "NATIONAL",
    employmentType: "Full-time",
    experienceLevel: "Entry-level",
    workMode: "ONSITE",
    description:
      "<p>The National Police Service is recruiting 10,000 police constables across all 47 counties. Successful candidates will undergo 9 months of training at Kiganjo Police Training College.</p>",
    tags: ["Government", "County", "Nakuru"],
    createdAt: "2025-01-15T09:00:00Z",
    deadline: "2025-02-20T23:59:00Z",
    featured: false,
  },
  {
    id: "gov-5",
    slug: "nairobi-county-health-workers-2025",
    title: "Nairobi County — Health Workers",
    companyName: "County Government of Nairobi",
    companyVerified: true,
    location: "Nairobi",
    county: "Nairobi",
    category: "Healthcare & Medical",
    listingType: "GOVERNMENT",
    governmentLevel: "COUNTY",
    employmentType: "Full-time",
    experienceLevel: "Mid-level",
    workMode: "ONSITE",
    description:
      "<p>Nairobi County is recruiting clinical officers, nurses, and public health officers for county health facilities.</p>",
    tags: ["Government", "County", "Health", "Nairobi"],
    createdAt: "2025-01-18T10:00:00Z",
    deadline: "2025-02-25T23:59:00Z",
    featured: false,
  },
  {
    id: "gov-6",
    slug: "mombasa-county-engineers-2025",
    title: "Mombasa County — Engineers",
    companyName: "County Government of Mombasa",
    companyVerified: true,
    location: "Mombasa",
    county: "Mombasa",
    category: "Engineering & Construction",
    listingType: "GOVERNMENT",
    governmentLevel: "COUNTY",
    employmentType: "Full-time",
    experienceLevel: "Mid-level",
    workMode: "ONSITE",
    description:
      "<p>Mombasa County is seeking Civil and Structural Engineers for infrastructure development projects including roads, drainage, and public buildings.</p>",
    tags: ["Government", "County", "Engineering", "Mombasa"],
    createdAt: "2025-01-20T08:00:00Z",
    deadline: "2025-03-05T23:59:00Z",
    featured: false,
  },
];

// ─── Casual & Part-Time ────────────────────────

export const casualJobs: Job[] = [
  {
    id: "cas-1",
    slug: "waitstaff-westlands-nairobi",
    title: "Waitstaff",
    companyName: "Westlands Restaurants Association",
    companyVerified: false,
    location: "Westlands, Nairobi",
    county: "Nairobi",
    category: "Hospitality & Tourism",
    listingType: "CASUAL",
    employmentType: "Part-time",
    experienceLevel: "Entry-level",
    workMode: "ONSITE",
    salaryMin: 500,
    salaryMax: 500,
    salaryPeriod: "day",
    description:
      "<p>Immediate opening for waitstaff at multiple restaurants in Westlands. No experience needed — training provided. Flexible hours available.</p>",
    tags: ["Casual", "Hospitality", "Immediate Start"],
    createdAt: "2025-02-01T06:00:00Z",
    deadline: null,
    featured: false,
  },
  {
    id: "cas-2",
    slug: "delivery-rider-cbd-nairobi",
    title: "Delivery Rider",
    companyName: "Quick Deliveries Ltd",
    companyVerified: false,
    location: "CBD, Nairobi",
    county: "Nairobi",
    category: "Logistics & Transport",
    listingType: "CASUAL",
    employmentType: "Part-time",
    experienceLevel: "Entry-level",
    workMode: "ONSITE",
    salaryMin: 1200,
    salaryMax: 1200,
    salaryPeriod: "day",
    description:
      "<p>Looking for motorcycle delivery riders for CBD and surrounding areas. Must own a motorcycle (Boda Boda) with valid license. Daily earnings potential.</p>",
    tags: ["Casual", "Delivery", "Own Bike"],
    createdAt: "2025-02-02T07:00:00Z",
    deadline: null,
    featured: false,
  },
  {
    id: "cas-3",
    slug: "farm-worker-naivasha",
    title: "Farm Worker",
    companyName: "Naivasha Flower Farms",
    companyVerified: false,
    location: "Naivasha",
    county: "Nakuru",
    category: "Agriculture & Farming",
    listingType: "CASUAL",
    employmentType: "Full-time",
    experienceLevel: "Entry-level",
    workMode: "ONSITE",
    salaryMin: 700,
    salaryMax: 700,
    salaryPeriod: "day",
    description:
      "<p>Farm workers needed for flower farm operations in Naivasha. Accommodation provided. Meals included during work hours.</p>",
    tags: ["Casual", "Farm", "Accommodation"],
    createdAt: "2025-01-28T06:00:00Z",
    deadline: null,
    featured: false,
  },
  {
    id: "cas-4",
    slug: "shop-assistant-thika-road-nairobi",
    title: "Shop Assistant",
    companyName: "Retail Solutions Kenya",
    companyVerified: false,
    location: "Thika Road, Nairobi",
    county: "Nairobi",
    category: "Retail & Wholesale",
    listingType: "CASUAL",
    employmentType: "Part-time",
    experienceLevel: "Entry-level",
    workMode: "ONSITE",
    salaryMin: 15000,
    salaryMax: 15000,
    salaryPeriod: "month",
    description:
      "<p>Part-time shop assistant needed for a retail outlet along Thika Road. Morning or afternoon shifts available.</p>",
    tags: ["Casual", "Retail", "Part-time"],
    createdAt: "2025-02-03T08:00:00Z",
    deadline: null,
    featured: false,
  },
  {
    id: "cas-5",
    slug: "cleaning-staff-kilimani-nairobi",
    title: "Cleaning Staff",
    companyName: "CleanPro Services",
    companyVerified: false,
    location: "Kilimani, Nairobi",
    county: "Nairobi",
    category: "Cleaning & Maintenance",
    listingType: "CASUAL",
    employmentType: "Part-time",
    experienceLevel: "Entry-level",
    workMode: "ONSITE",
    salaryMin: 600,
    salaryMax: 600,
    salaryPeriod: "day",
    description:
      "<p>Weekend cleaning staff needed for offices and apartments in Kilimani area. Experience preferred but not required.</p>",
    tags: ["Casual", "Cleaning", "Weekends"],
    createdAt: "2025-02-01T09:00:00Z",
    deadline: null,
    featured: false,
  },
  {
    id: "cas-6",
    slug: "loader-industrial-area-nairobi",
    title: "Loader",
    companyName: "Logistics Hub Ltd",
    companyVerified: false,
    location: "Industrial Area, Nairobi",
    county: "Nairobi",
    category: "Logistics & Transport",
    listingType: "CASUAL",
    employmentType: "Part-time",
    experienceLevel: "Entry-level",
    workMode: "ONSITE",
    salaryMin: 800,
    salaryMax: 800,
    salaryPeriod: "day",
    description:
      "<p>Morning shift loaders needed for a busy warehouse in Industrial Area. Must be physically fit.</p>",
    tags: ["Casual", "Warehouse", "Morning Shift"],
    createdAt: "2025-02-04T06:00:00Z",
    deadline: null,
    featured: false,
  },
];

// ─── Opportunities Hub (Internships) ───────────

export const opportunityInternships: Job[] = [
  {
    id: "opp-int-1",
    slug: "finance-intern-equity-bank-nairobi",
    title: "Finance Intern — Equity Bank",
    companyName: "Equity Bank",
    companyVerified: true,
    location: "Nairobi",
    county: "Nairobi",
    category: "Finance & Accounting",
    listingType: "OPPORTUNITY",
    opportunityType: "INTERNSHIP",
    employmentType: "Internship",
    experienceLevel: "Entry-level",
    workMode: "ONSITE",
    description:
      "<p>3-month internship in Equity Bank's Finance department. Gain hands-on experience in financial analysis, reporting, and planning.</p>",
    tags: ["Internship", "Finance", "Banking"],
    createdAt: "2025-01-25T10:00:00Z",
    deadline: "2025-03-15T23:59:00Z",
    featured: false,
  },
  {
    id: "opp-int-2",
    slug: "software-intern-safaricom-nairobi",
    title: "Software Intern — Safaricom",
    companyName: "Safaricom",
    companyVerified: true,
    location: "Nairobi",
    county: "Nairobi",
    category: "Software Engineering",
    listingType: "OPPORTUNITY",
    opportunityType: "INTERNSHIP",
    employmentType: "Internship",
    experienceLevel: "Entry-level",
    workMode: "HYBRID",
    description:
      "<p>6-month software engineering internship at Safaricom's Innovation Lab. Work on cutting-edge projects in mobile, cloud, and AI.</p>",
    tags: ["Internship", "Software Engineering", "Tech"],
    createdAt: "2025-01-20T08:00:00Z",
    deadline: "2025-03-10T23:59:00Z",
    featured: false,
  },
  {
    id: "opp-int-3",
    slug: "marketing-intern-eabl-nairobi",
    title: "Marketing Intern — EABL",
    companyName: "East African Breweries",
    companyVerified: true,
    location: "Nairobi",
    county: "Nairobi",
    category: "Marketing & Communications",
    listingType: "OPPORTUNITY",
    opportunityType: "INTERNSHIP",
    employmentType: "Internship",
    experienceLevel: "Entry-level",
    workMode: "ONSITE",
    description:
      "<p>Join EABL's marketing team for a 3-month internship. Work on brand campaigns, digital marketing, and consumer engagement.</p>",
    tags: ["Internship", "Marketing", "FMCG"],
    createdAt: "2025-01-22T11:00:00Z",
    deadline: "2025-03-20T23:59:00Z",
    featured: false,
  },
];

// ─── Opportunities Tabs ────────────────────────

export const entryLevelJobs: Job[] = [
  {
    id: "tab-e-1",
    slug: "junior-accountant-coop-bank-nairobi",
    title: "Junior Accountant",
    companyName: "Co-operative Bank",
    companyVerified: true,
    location: "Nairobi",
    county: "Nairobi",
    category: "Finance & Accounting",
    listingType: "JOB",
    employmentType: "Full-time",
    experienceLevel: "Entry-level",
    workMode: "ONSITE",
    description:
      "<p>Entry-level accounting position at Co-operative Bank. Handle day-to-day bookkeeping, reconciliation, and financial reporting.</p>",
    tags: ["Entry Level", "Accounting", "Banking"],
    createdAt: "2025-01-30T10:00:00Z",
    deadline: "2025-03-15T23:59:00Z",
    featured: false,
  },
  {
    id: "tab-e-2",
    slug: "customer-service-rep-safaricom-nairobi",
    title: "Customer Service Representative",
    companyName: "Safaricom",
    companyVerified: true,
    location: "Nairobi",
    county: "Nairobi",
    category: "Customer Service",
    listingType: "JOB",
    employmentType: "Full-time",
    experienceLevel: "Entry-level",
    workMode: "ONSITE",
    description:
      "<p>Handle customer inquiries via phone, chat, and email. Resolve issues related to M-Pesa, data, and voice services.</p>",
    tags: ["Entry Level", "Customer Service", "Call Center"],
    createdAt: "2025-02-01T09:00:00Z",
    deadline: "2025-03-20T23:59:00Z",
    featured: false,
  },
  {
    id: "tab-e-3",
    slug: "data-entry-clerk-kra-nairobi",
    title: "Data Entry Clerk",
    companyName: "KRA",
    companyVerified: true,
    location: "Nairobi",
    county: "Nairobi",
    category: "Administration & Office",
    listingType: "GOVERNMENT",
    governmentLevel: "NATIONAL",
    employmentType: "Contract",
    experienceLevel: "Entry-level",
    workMode: "ONSITE",
    description:
      "<p>Enter and verify taxpayer data into KRA's iTax system. Ensure accuracy and completeness of records.</p>",
    tags: ["Entry Level", "Data Entry", "Government"],
    createdAt: "2025-01-28T07:00:00Z",
    deadline: "2025-03-10T23:59:00Z",
    featured: false,
  },
  {
    id: "tab-e-4",
    slug: "marketing-assistant-eabl-nairobi",
    title: "Marketing Assistant",
    companyName: "EABL",
    companyVerified: true,
    location: "Nairobi",
    county: "Nairobi",
    category: "Marketing & Communications",
    listingType: "JOB",
    employmentType: "Full-time",
    experienceLevel: "Entry-level",
    workMode: "ONSITE",
    description:
      "<p>Support the marketing team with campaign execution, social media management, and event coordination.</p>",
    tags: ["Entry Level", "Marketing", "FMCG"],
    createdAt: "2025-02-02T10:00:00Z",
    deadline: "2025-03-25T23:59:00Z",
    featured: false,
  },
];

export const internshipJobs: Job[] = [
  {
    id: "tab-i-1",
    slug: "finance-intern-equity-bank-nairobi-2",
    title: "Finance Intern",
    companyName: "Equity Bank",
    companyVerified: true,
    location: "Nairobi",
    county: "Nairobi",
    category: "Finance & Accounting",
    listingType: "OPPORTUNITY",
    opportunityType: "INTERNSHIP",
    employmentType: "Internship",
    experienceLevel: "Entry-level",
    workMode: "ONSITE",
    description:
      "<p>3-month paid internship in Equity Bank's Finance division. Get exposure to financial reporting, budgeting, and analysis.</p>",
    tags: ["Internship", "Finance", "Banking"],
    createdAt: "2025-01-25T10:00:00Z",
    deadline: "2025-03-15T23:59:00Z",
    featured: false,
  },
  {
    id: "tab-i-2",
    slug: "software-engineering-intern-safaricom-nairobi",
    title: "Software Engineering Intern",
    companyName: "Safaricom",
    companyVerified: true,
    location: "Nairobi",
    county: "Nairobi",
    category: "Software Engineering",
    listingType: "OPPORTUNITY",
    opportunityType: "INTERNSHIP",
    employmentType: "Internship",
    experienceLevel: "Entry-level",
    workMode: "HYBRID",
    description:
      "<p>6-month internship at Safaricom's Innovation Lab. Work on real products used by millions of Kenyans.</p>",
    tags: ["Internship", "Software Engineering", "Tech"],
    createdAt: "2025-01-20T08:00:00Z",
    deadline: "2025-03-10T23:59:00Z",
    featured: false,
  },
];

export const scholarshipJobs: Job[] = [
  {
    id: "tab-s-1",
    slug: "mastercard-foundation-scholars-uon",
    title: "Mastercard Foundation Scholars",
    companyName: "University of Nairobi",
    companyVerified: true,
    location: "Nairobi",
    county: "Nairobi",
    category: "Education & Training",
    listingType: "OPPORTUNITY",
    opportunityType: "SCHOLARSHIP",
    employmentType: "Full-time",
    experienceLevel: "Entry-level",
    workMode: "ONSITE",
    salaryMin: 0,
    salaryMax: 0,
    description:
      "<p>Full scholarship for undergraduate studies at the University of Nairobi. Covers tuition, accommodation, books, and a living stipend. Open to academically talented yet economically disadvantaged students from Kenya.</p>",
    tags: ["Scholarship", "University", "Full Scholarship"],
    createdAt: "2025-01-15T09:00:00Z",
    deadline: "2025-02-28T23:59:00Z",
    featured: false,
  },
  {
    id: "tab-s-2",
    slug: "kcb-foundation-scholarship-2025",
    title: "KCB Foundation Scholarship",
    companyName: "KCB Group",
    companyVerified: true,
    location: "Nairobi",
    county: "Nairobi",
    category: "Education & Training",
    listingType: "OPPORTUNITY",
    opportunityType: "SCHOLARSHIP",
    employmentType: "Full-time",
    experienceLevel: "Entry-level",
    workMode: "ONSITE",
    description:
      "<p>KCB Foundation offers tuition and stipend support for students pursuing diploma and degree programs in STEM, business, and agriculture at accredited Kenyan universities.</p>",
    tags: ["Scholarship", "Tuition", "STEM"],
    createdAt: "2025-01-20T08:00:00Z",
    deadline: "2025-03-15T23:59:00Z",
    featured: false,
  },
];
